language: php

php:
    - 5.2
    - 5.3
    - 5.4
    - 5.5
    - 5.6

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.6 WP_MULTISITE=0
    - WP_VERSION=3.6 WP_MULTISITE=1

matrix:
    exclude:
        - php: 5.5
          env: WP_VERSION=3.6 WP_MULTISITE=0
        - php: 5.5
          env: WP_VERSION=3.6 WP_MULTISITE=1
        - php: 5.6
          env: WP_VERSION=3.6 WP_MULTISITE=0
        - php: 5.6
          env: WP_VERSION=3.6 WP_MULTISITE=1

before_script:
    - export WP_TESTS_DIR=/tmp/wordpress-tests/
    - bash install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 
    - composer install --dev
    - vendor/tedivm/dovecottesting/SetupEnvironment.sh

script: phpunit
